server:
  port : 8081

spring:
  redis:
    database: 2
    host: 47.98.143.120
    port: 63444
    password : 12Ajinshi
    timeout : 5000
    pool:
      max-active : 8
      max-wait : 1
      max-idle : 8
      min-idle : 0
  application:
    name: orderSys
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.143.120:3306/order?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password : 10Ajinshi
    initialSize : 5
    minIdle : 5
    maxActive : 200
    maxWait : 60000
    timeBetweenEvictionRunsMillis : 6000
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters : stat,wall,log4j
    connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  type-aliases-package : com.zy.device.entity
  config-locations : classpath:mybatis-config.xml
  mapper-locations : classpath:com/zy/device/mapper/*.xml


